// ============================================
// Image Analysis Service
// Uses OpenAI Vision, Gemini Vision, or Rule-based Fallback
// ============================================

import ImageAnalysis from '../models/ImageAnalysis.js';

const parseJSONResponse = (text) => {
  try {
    if (!text) throw new Error('No text provided');
    
    // Strip <think>...</think> blocks generated by DeepSeek reasoning models
    const cleanText = text.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

    // Extract the first valid JSON object using regex, ignoring surrounding conversational text
    const match = cleanText.match(/\{[\s\S]*\}/);
    if (!match) throw new Error('No JSON object found in response');
    
    // Fix trailing commas in JSON which causes JSON.parse to fail
    const jsonStr = match[0].replace(/,\s*([}\]])/g, '$1');
    return JSON.parse(jsonStr);
  } catch (error) {
    console.error('❌ Failed to parse AI JSON response:', error.message);
    return null;
  }
};

/**
 * Smart rule-based fallback analysis if no AI keys are provided.
 * Analyzes item name and description to extract likely labels and colors.
 *
 * @param {string} itemName
 * @param {string} description
 * @returns {object} Analysis result
 */
const getFallbackAnalysis = (itemName = '', description = '') => {
  const combined = `${itemName} ${description}`.toLowerCase();
  
  // Basic colors list
  const colorList = ['black', 'white', 'blue', 'red', 'green', 'yellow', 'grey', 'gray', 'silver', 'gold', 'brown', 'pink', 'purple', 'orange'];
  const colors = colorList.filter(color => combined.includes(color));

  // Basic categories / labels extraction
  const labelKeywords = {
    phone: ['phone', 'iphone', 'samsung', 'android', 'mobile', 'cellphone'],
    laptop: ['laptop', 'macbook', 'dell', 'hp', 'lenovo', 'computer', 'asus'],
    keys: ['key', 'keys', 'keychain'],
    wallet: ['wallet', 'purse', 'cardholder', 'billfold'],
    watch: ['watch', 'smartwatch', 'applewatch', 'rolex', 'casio'],
    bag: ['bag', 'backpack', 'handbag', 'suitcase', 'briefcase'],
    charger: ['charger', 'cable', 'adapter', 'powerbank', 'wire'],
    headphones: ['headphones', 'earbuds', 'airpods', 'headset'],
    clothing: ['jacket', 'coat', 'shirt', 'cap', 'hat', 'hoodie', 'sweater', 'shoe', 'shoes'],
    documents: ['id card', 'student card', 'passport', 'license', 'book', 'notebook', 'document']
  };

  const labels = [];
  // Add item name words as labels
  itemName.toLowerCase().split(/\s+/).forEach(word => {
    const cleanWord = word.replace(/[^a-z]/g, '');
    if (cleanWord.length > 2 && !['and', 'for', 'with', 'lost', 'found'].includes(cleanWord)) {
      labels.push(cleanWord);
    }
  });

  // Check matching keyword groups
  Object.entries(labelKeywords).forEach(([label, keywords]) => {
    if (keywords.some(keyword => combined.includes(keyword))) {
      if (!labels.includes(label)) {
        labels.push(label);
      }
    }
  });

  // Default labels if empty
  if (labels.length === 0) {
    labels.push('item', 'personal object');
  }

  // Capitalize labels and colors
  const finalLabels = labels.map(l => l.charAt(0).toUpperCase() + l.slice(1));
  const finalColors = colors.map(c => c.charAt(0).toUpperCase() + c.slice(1));

  return {
    labels: finalLabels,
    colors: finalColors.length > 0 ? finalColors : ['Unknown'],
    description: `Rule-based analysis for: ${itemName}. ${description.substring(0, 100)}`,
    confidence: 70,
    provider: 'fallback'
  };
};

const fetchFromAI = async (messages, type = 'text', format = null) => {
  const OPENROUTER_KEY = process.env.OPENROUTER_API_KEY;
  const PRIMARY_KEY = process.env.AI_API_KEY || OPENROUTER_KEY;

  if (!PRIMARY_KEY || PRIMARY_KEY === 'your_openrouter_api_key') return null;

  const primaryUrl = process.env.AI_API_URL || 'https://openrouter.ai/api/v1/chat/completions';
  const fallbackUrl = 'https://openrouter.ai/api/v1/chat/completions';

  // Define models based on task type
  let primaryModel = process.env.AI_CHAT_MODEL || 'meta-llama/llama-3.3-70b-instruct:free';
  let fallbackModel = 'meta-llama/llama-3.3-70b-instruct:free';

  if (type === 'vision') {
    primaryModel = process.env.AI_VISION_MODEL || 'meta-llama/llama-3.2-11b-vision-instruct:free';
    fallbackModel = 'nvidia/nemotron-nano-12b-v2-vl:free'; // Reliable free vision backup
  }

  const reqBody = { model: primaryModel, messages };

  const headers = {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${PRIMARY_KEY}`,
    'HTTP-Referer': process.env.CLIENT_URL || 'http://localhost:3000',
    'X-Title': 'Smart Lost and Found'
  };

  try {
    const res = await fetch(primaryUrl, { method: 'POST', headers, body: JSON.stringify(reqBody) });
    if (res.ok) {
      const text = await res.text();
      try {
        return JSON.parse(text);
      } catch (e) {
        throw new Error('Invalid JSON from Primary Provider');
      }
    }
    const errText = await res.text();
    throw new Error(`Primary Provider Failed: ${res.status} - ${errText}`);
  } catch (err) {
    console.warn(`⚠️ AI Primary Provider Failed for ${type} task (${err.message}). Falling back to OpenRouter...`);
    if (OPENROUTER_KEY && OPENROUTER_KEY !== 'your_openrouter_api_key') {
      reqBody.model = fallbackModel;
      headers.Authorization = `Bearer ${OPENROUTER_KEY}`;
      const fallbackRes = await fetch(fallbackUrl, { method: 'POST', headers, body: JSON.stringify(reqBody) });
      if (fallbackRes.ok) {
        const text = await fallbackRes.text();
        try {
          return JSON.parse(text);
        } catch (e) {
          throw new Error(`Primary Failed (${err.message}) AND Fallback Provider returned non-JSON`);
        }
      } else {
        const errText = await fallbackRes.text();
        throw new Error(`Primary Failed (${err.message}) AND Fallback Provider Failed: ${fallbackRes.status} - ${errText}`);
      }
    }
    throw new Error(`Primary API Failed: ${err.message}. (No Fallback API key provided)`);
  }
};

/**
 * Analyze an item image using OpenRouter.
 */
const analyzeWithOpenRouter = async (imageUrl) => {
  try {
    const messages = [
      {
        role: 'user',
        content: [
          { type: 'text', text: 'Analyze this lost/found item image. Return a JSON object with strictly these fields: "labels" (array of strings, ALWAYS lowercase, separate brand names from generic items, e.g. ["iphone 13 pro", "apple", "smartphone", "cracked screen"]), "colors" (array of strings, ALWAYS lowercase, e.g. ["space grey", "black"]), "description" (a highly detailed 1-2 sentence description including unique visual features, brands, or damage), and "confidence" (number 0-100 representing how confident you are). Do not wrap the JSON in markdown blocks.' },
          { type: 'image_url', image_url: { url: imageUrl } }
        ]
      }
    ];

    const data = await fetchFromAI(messages, 'vision');
    const content = data?.choices?.[0]?.message?.content;
    const result = parseJSONResponse(content);
    
    if (result) {
      return { ...result, provider: 'ai', rawResponse: data };
    }
    return null;
  } catch (error) {
    console.error('❌ AI Image Analysis failed:', error.message);
    return null;
  }
};

/**
 * Analyze an item image and persist the results.
 * Falls back gracefully to rule-based fallback if APIs fail or keys are missing.
 *
 * @param {string} itemType - 'LostItem' or 'FoundItem'
 * @param {string} itemId - Mongoose ObjectId
 * @param {string} imageUrl - URL of the image
 * @param {string} itemName - Fallback item name
 * @param {string} description - Fallback description
 * @returns {Promise<ImageAnalysis>} Saved ImageAnalysis document
 */
const analyzeItemImage = async (itemType, itemId, imageUrl, itemName = '', description = '') => {
  let analysis = null;

  if (!imageUrl.startsWith('data:')) {
    console.log(`🤖 Analyzing image for ${itemType} (${itemId}) using AI...`);
    analysis = await analyzeWithOpenRouter(imageUrl);
  }

  if (!analysis) {
    console.log(`ℹ️ Using rule-based fallback analysis for ${itemType} (${itemId})...`);
    analysis = getFallbackAnalysis(itemName, description);
  }

  const savedAnalysis = await ImageAnalysis.findOneAndUpdate(
    { itemId, itemType },
    {
      imageUrl,
      labels: analysis.labels || [],
      colors: analysis.colors || [],
      description: analysis.description || '',
      confidence: analysis.confidence || 0,
      provider: analysis.provider || 'fallback',
      rawResponse: analysis.rawResponse || null
    },
    { new: true, upsert: true }
  );

  console.log(`✅ Image analysis completed and saved for ${itemType} (${itemId}). Provider: ${savedAnalysis.provider}`);
  return savedAnalysis;
};

/**
 * Generate an icon and description for a newly suggested category using AI.
 * Falls back to generic defaults if APIs are unavailable or fail.
 *
 * @param {string} categoryName - The name of the category
 * @returns {Promise<{icon: string, description: string}>}
 */
const generateCategoryDetails = async (categoryName) => {
  const systemPrompt = `You are an AI for a Lost and Found system. A user suggested a new category named "${categoryName}".
First, evaluate if this is a realistic physical object or a valid category of objects that someone could lose or find. 
If it is gibberish (e.g. "loahhfafafaf"), a digital concept/game (e.g. "gta"), or meaningless, return ONLY: {"isValid": false}.
If it is valid, return ONLY a JSON object with fields: "isValid": true, "icon" (a single relevant emoji), and "description" (a concise 1-sentence description). Example: {"isValid":true,"icon":"🛹","description":"Skateboards and accessories."}`;
  
  let data;
  try {
    data = await fetchFromAI([{ role: 'user', content: systemPrompt }], 'text', { type: 'json_object' });
  } catch (err) {
    console.error(`AI Category Suggestion API Error: ${err.message}`);
    return { icon: '📦', description: `Items related to ${categoryName}.` };
  }

  const content = data?.choices?.[0]?.message?.content;
  const result = parseJSONResponse(content);
  
  if (result && result.isValid === false) {
    throw new Error('INVALID_CATEGORY');
  }

  if (result && result.icon && result.description) return result;

  console.error(`AI Category Suggestion Parse Failed. Raw content: ${content}`);
  return { icon: '📦', description: `Items related to ${categoryName}.` };
};

/**
 * Auto-suggests item details from an image for frontend form auto-fill.
 */
const suggestDetailsFromImage = async (imageUrl) => {
  const systemPrompt = `You are an AI assistant helping a user fill out a Lost and Found report. 
First, evaluate if this image is a valid physical object that could be lost or found. If the image is a human face/selfie, a meme, completely blank, explicit/NSFW, or otherwise clearly not an object, you must flag it as spam.

Return ONLY a valid JSON object with these exact fields:
- "isSpam": Boolean (true if the image is a selfie, meme, explicit, or blank, false otherwise).
- "itemName": A concise title (max 5 words, e.g. "Apple iPhone 13 Pro Black"). If isSpam is true, leave empty.
- "category": The most appropriate category (e.g. "Electronics", "Wallets", "Keys", "Bags", "Clothing", "Documents", "Other"). If isSpam is true, leave empty.
- "description": A short descriptive paragraph suitable for a lost/found report. If isSpam is true, write a reason why it was rejected.
- "tags": A comma-separated string of 3 to 5 search keywords. If isSpam is true, leave empty.`;

  const messages = [
    {
      role: 'user',
      content: [
        { type: 'text', text: systemPrompt },
        { type: 'image_url', image_url: { url: imageUrl } }
      ]
    }
  ];

  const data = await fetchFromAI(messages, 'vision', { type: 'json_object' });
  const content = data?.choices?.[0]?.message?.content;
  const result = parseJSONResponse(content);

  if (result && (result.itemName || result.isSpam)) {
    console.log(`✅ AI suggestion success`);
    return result;
  }
  throw new Error('All AI models failed to generate suggestions.');
};

/**
 * Generates searchable English keywords from an item's name and description.
 * Capable of translating from Sinhala, Tamil, or Singlish to English.
 */
const generateKeywordsFromText = async (itemName, description) => {
  const systemPrompt = `You are a translation and keyword extraction assistant. 
A user has reported a lost or found item. The item name is "${itemName}" and the description is "${description}".
The text might be in English, Sinhala, Tamil, or Singlish (Sinhala written in English letters, e.g. "mage phone eka nathi wuna", "kalu pata kudayak").

Your task:
1. Understand the language and translate the meaning into English.
2. Extract 5-10 highly relevant search keywords in English (e.g., color, brand, item type, unique features).

Return ONLY a valid JSON object with the field "keywords" containing an array of lowercase strings. Example: {"keywords": ["iphone 13", "black", "apple", "smartphone", "cracked screen"]}`;

  const data = await fetchFromAI([{ role: 'user', content: systemPrompt }], 'text', { type: 'json_object' });
  const content = data?.choices?.[0]?.message?.content;
  const result = parseJSONResponse(content);

  if (result && Array.isArray(result.keywords)) {
    return result.keywords;
  }
  return [];
};

export {
  analyzeItemImage,
  generateCategoryDetails,
  suggestDetailsFromImage,
  generateKeywordsFromText,
  // Export these for testing if needed
  parseJSONResponse
};
